# Generated by Django 6.0.6 on 2026-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
