# Generated by Django 6.0.6 on 2026-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
