# Generated by Django 6.0.6 on 2026-08-26 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pharmacy.medicine'),
        ),
    ]
