# Generated by Django 6.0.6 on 2026-09-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_procustomersale'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
