# Generated by Django 6.0.6 on 2026-09-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_medicine_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
