# Generated by Django 6.0.6 on 2026-09-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_purchase_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='invoice_number',
        ),
    ]
