# Generated by Django 6.0.6 on 2026-09-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_medicine_total_dis_price_purchase_total_dis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
